class Match < ActiveRecord::Base
	has_many :notes, dependent: :destroy

	validates :team_number, presence: true
	validates :red_1, presence: true
	validates :red_2, presence: true
	validates :red_3, presence: true
	validates :blue_1, presence: true
	validates :blue_2, presence: true
	validates :blue_3, presence: true
	validates :scouter_email, presence: true
	validates :top_made_tele, presence: true
	validates :top_missed_tele, presence: true
	validates :low_made_tele, presence: true
	validates :hot_auton, presence: true
	validates :drive_auton, presence: true
	validates :top_made_auton, presence: true
	validates :top_missed_auton, presence: true
	validates :low_made_auton, presence: true
	validates :low_missed_auton, presence: true
	validates :catch_made, presence: true
	validates :catch_missed, presence: true
	validates :truss_made, presence: true
	validates :truss_missed, presence: true
	validates :static_pickup, presence: true
	validates :moving_pickup, presence: true
	validates :attempted_passes, presence: true
	validates :accurate_passes, presence: true
	validates :attempted_receptions, presence: true
	validates :good_receptions, presence: true
	validates :human_player_skill, presence: true
	validates :goalie_blocked, presence: true
	validates :goalie_failed, presence: true
	validates :goalie_block_area, presence: true
	validates :pure_defense, presence: true
	validates :def_passes_interrupted, presence: true
	validates :def_time_drain, presence: true
	validates :speed, presence: true
	validates :driver_skill, presence: true
	validates :when_not_offense, presence: true
	validates :no_show, presence: true
	validates :dead, presence: true
end
